import { prisma, withTenantTx } from '@seredina/db';

/**
 * "Full data portability -- a one-click export in an open format" (docs/ROADMAP.md):
 * the honest opposite of how a vendor whose business model depends on lock-in
 * treats migrating away. Every tenant-scoped table (see
 * packages/db/src/prisma.ts's TENANT_SCOPE_FIELD) is included, EXCEPT:
 *   - secrets: User.passwordHash, ApiKey.hashedKey, EmailChannel's
 *     encrypted password and OAuth secret/token fields, Webhook.secretEncrypted, TenantSsoSettings' client secret -- explicit `select`
 *     allowlists on those five models, never a denylist, so a future field
 *     added to any of them can't silently leak into an export by default.
 *   - Notification and DiscoveryJob rows -- transient inbox/scan-job state,
 *     not data or configuration a tenant would need to migrate or restore.
 * One withTenantTx, every query a plain read -- no external I/O, so running
 * all of it in one transaction is safe and fast, the same reasoning every
 * other multi-table read in this codebase already follows.
 * See docs/adr/0024-data-export.md.
 */
export async function exportTenantData(tenantId: string) {
  return withTenantTx(prisma, tenantId, async (tx) => {
    const [
      tenant,
      roles,
      rolePermissions,
      users,
      teams,
      contacts,
      ticketStatuses,
      tickets,
      messages,
      apiKeys,
      assets,
      ticketAssets,
      emailChannels,
      customFieldDefinitions,
      manufacturers,
      assetModels,
      processTemplates,
      processStepTemplates,
      processInstances,
      processStepInstances,
      webhooks,
      macros,
      slaPolicies,
      businessHours,
      dashboardWidgets,
      problems,
      serviceCatalogItems,
      services,
      serviceAssets,
      kbArticles,
      onCallSchedules,
      onCallShifts,
      escalationTiers,
      escalationRuns,
      savedViews,
      notificationPreferences,
      aiUsageLogs,
      contracts,
      contractAssets,
      auditLogs,
      ssoSettings,
      organizations,
      directoryContacts,
      contractPayments,
    ] = await Promise.all([
      tx.tenant.findUniqueOrThrow({ where: { id: tenantId } }),
      tx.role.findMany(),
      tx.rolePermission.findMany(),
      tx.user.findMany({
        select: {
          id: true,
          email: true,
          name: true,
          roleId: true,
          createdAt: true,
          failedLoginAttempts: true,
          lockedUntil: true,
        },
      }),
      tx.team.findMany(),
      tx.contact.findMany(),
      tx.ticketStatus.findMany(),
      tx.ticket.findMany(),
      tx.message.findMany(),
      tx.apiKey.findMany({ select: { id: true, name: true, createdAt: true, lastUsedAt: true } }),
      tx.asset.findMany(),
      tx.ticketAsset.findMany(),
      tx.emailChannel.findMany({
        select: {
          id: true,
          name: true,
          fromAddress: true,
          imapHost: true,
          imapPort: true,
          imapSecure: true,
          imapUsername: true,
          smtpHost: true,
          smtpPort: true,
          smtpSecure: true,
          smtpUsername: true,
          isActive: true,
          lastPolledAt: true,
          createdAt: true,
          authType: true,
          connectionStatus: true,
          oauthClientId: true,
          oauthMicrosoftTenant: true,
        },
      }),
      tx.customFieldDefinition.findMany(),
      tx.manufacturer.findMany(),
      tx.assetModel.findMany(),
      tx.processTemplate.findMany(),
      tx.processStepTemplate.findMany(),
      tx.processInstance.findMany(),
      tx.processStepInstance.findMany(),
      tx.webhook.findMany({
        select: {
          id: true,
          url: true,
          events: true,
          isActive: true,
          createdAt: true,
          lastDeliveryAt: true,
          lastDeliveryStatus: true,
        },
      }),
      tx.macro.findMany(),
      tx.slaPolicy.findMany(),
      tx.businessHours.findMany(),
      tx.dashboardWidget.findMany(),
      tx.problem.findMany(),
      tx.serviceCatalogItem.findMany(),
      tx.service.findMany(),
      tx.serviceAsset.findMany(),
      tx.kbArticle.findMany(),
      tx.onCallSchedule.findMany(),
      tx.onCallShift.findMany(),
      tx.escalationTier.findMany(),
      tx.escalationRun.findMany(),
      tx.savedView.findMany(),
      tx.notificationPreference.findMany(),
      tx.aiUsageLog.findMany(),
      tx.contract.findMany(),
      tx.contractAsset.findMany(),
      tx.auditLog.findMany({ orderBy: { createdAt: 'asc' } }),
      // Allowlist, like the other models with a secret: never the client secret.
      tx.tenantSsoSettings.findMany({
        select: {
          id: true,
          enabled: true,
          provider: true,
          issuer: true,
          clientId: true,
          allowedDomains: true,
          autoProvision: true,
          defaultRoleKey: true,
          enforced: true,
          createdAt: true,
          updatedAt: true,
        },
      }),
      // docs/adr/0076-directory-payments-inventory.md
      tx.organization.findMany(),
      tx.directoryContact.findMany(),
      tx.contractPayment.findMany(),
    ]);

    return {
      exportedAt: new Date().toISOString(),
      tenant,
      roles,
      rolePermissions,
      users,
      teams,
      contacts,
      ticketStatuses,
      tickets,
      messages,
      apiKeys,
      assets,
      ticketAssets,
      emailChannels,
      customFieldDefinitions,
      manufacturers,
      assetModels,
      processTemplates,
      processStepTemplates,
      processInstances,
      processStepInstances,
      webhooks,
      macros,
      slaPolicies,
      businessHours,
      dashboardWidgets,
      problems,
      serviceCatalogItems,
      services,
      serviceAssets,
      kbArticles,
      onCallSchedules,
      onCallShifts,
      escalationTiers,
      escalationRuns,
      savedViews,
      notificationPreferences,
      aiUsageLogs,
      contracts,
      contractAssets,
      auditLogs,
      ssoSettings,
      organizations,
      directoryContacts,
      contractPayments,
    };
  });
}
